---
- hosts: localhost
  become: true
  gather_facts: False

  vars:
    region: us-east-2
    instance_type: t2.micro
    ami: ami-0e472ba40eb589f49
    hosts_file: /etc/ansible/hosts
    access_key: 
    secret_key: 

  tasks:
   - name: Create security group
     ec2_group:
       aws_access_key: "{{ access_key }}"
       aws_secret_key: "{{ secret_key }}"
       name: "sonal-sg"
       description: "Sonal Security Group"
       region: "{{ region }}"
       rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

   - name: Create an EC2 key
     ec2_key:
       aws_access_key: "{{ access_key }}"
       aws_secret_key: "{{ secret_key }}"
       name: "sonal"
       region: "{{ region }}"
     register: ec2_key
   - name: Save private key (PEM file)
     copy: content="{{ec2_key.key.private_key}}" dest=/tmp/sonal.pem mode=0600
     when: ec2_key.changed
   - name: Create an ec2 instance
     ec2:
       aws_access_key: "{{ access_key }}"
       aws_secret_key: "{{ secret_key }}"
       key_name: sonal
       group: sonal-sg # security group name
       instance_type: "{{ instance_type}}"
       image: "{{ ami }}"
       wait: true
       region: "{{ region }}"
       count: 1 # default
       count_tag:
         Name: Sonal-demo
       instance_tags:
         Name: Sonal-demo
     register: ec2
   - name: Save IP to inventory file
     lineinfile:
       dest: "{{hosts_file}}"
       insertafter: '\[web\]'
       line: "{{item.private_ip}}"
     with_items: "{{ec2.instances}}"
